# Generated by Django 3.1 on 2020-11-10 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20201109_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bookitems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.bookitems'),
        ),
    ]
