# Generated by Django 3.1 on 2020-11-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20201110_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='bookitems',
        ),
        migrations.AddField(
            model_name='purchase',
            name='bookitems',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
