# Generated by Django 3.1 on 2020-11-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20201110_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='bookitems',
        ),
        migrations.AddField(
            model_name='purchase',
            name='bookitems',
            field=models.ManyToManyField(blank=True, null=True, to='book.BookItems'),
        ),
    ]
