# Generated by Django 3.1 on 2020-11-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20201110_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='bookitems',
        ),
    ]
