# Generated by Django 3.1 on 2020-10-31 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20201031_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.cart'),
        ),
    ]
