# Generated by Django 3.1 on 2020-10-10 14:06

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201010_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='contact phone number', max_length=31, null=True),
        ),
    ]
