# Generated by Django 3.1 on 2020-10-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201012_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
    ]
